openapi: 3.0.2
info:
  contact:
    email: opensource@vwt.digital
    name: VolkerWessels Telecom - Digital Ambition Team
    url: https://vwt-digital.github.io/
  description: Endpoint to retreive all DAT Monitoring metrics
  license:
    name: GNU GPLv3
    url: https://www.gnu.org/licenses/gpl.txt
  title: Monitoring
  version: 1.0.0
servers:
- url: https://PROJECT_ID.appspot.com/
security:
- ApiKeyAuth: []
paths:
  /build-statuses-other:
    get:
      description: Get a list of last 20 other build statuses
      operationId: build_statuses_other_get
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/BuildOtherStatus'
                type: array
          description: Scheme with multiple other build statuses
        204:
          description: No content
      summary: Get last 20 other build statuses
      x-openapi-router-controller: openapi_server.controllers.buildstatuses_controller
  /build-statuses-triggers:
    get:
      description: Get a list of all build trigger statuses
      operationId: build_statuses_triggers_get
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/BuildTriggerStatus'
                type: array
          description: Scheme with multiple build trigger statuses
        204:
          description: No content
      summary: Get all build trigger statuses
      x-openapi-router-controller: openapi_server.controllers.buildstatuses_controller
  /error-reporting:
    get:
      description: Get a list of last 20 error reportings
      operationId: error_reporting_get
      responses:
        200:
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ErrorReport'
                type: array
          description: Scheme with multiple error reportings
        204:
          description: No content
      summary: Get last 20 error reportings
      x-openapi-router-controller: openapi_server.controllers.errorreporting_controller
components:
  responses:
    BuildTriggerStatuses:
      content:
        application/json:
          schema:
            items:
              $ref: '#/components/schemas/BuildTriggerStatus'
            type: array
      description: Scheme with multiple build trigger statuses
    BuildOtherStatuses:
      content:
        application/json:
          schema:
            items:
              $ref: '#/components/schemas/BuildOtherStatus'
            type: array
      description: Scheme with multiple other build statuses
    ErrorReporting:
      content:
        application/json:
          schema:
            items:
              $ref: '#/components/schemas/ErrorReport'
            type: array
      description: Scheme with multiple error reportings
  schemas:
    BuildTriggerStatus:
      example:
        branch: develop
        git_source: github
        organization: vwt-digital
        project_id: random-project-id
        repo_name: random-repo-name
        status: passing
        updated: 2019-09-01T12:00:00+02:00
      properties:
        branch:
          type: string
        git_source:
          type: string
        organization:
          type: string
        project_id:
          type: string
        repo_name:
          type: string
        status:
          enum:
          - pending
          - failing
          - passing
          type: string
        updated:
          format: date-time
          type: string
      required:
      - branch
      - git_source
      - organization
      - project_id
      - repo_name
      - status
      - updated
      type: object
    BuildOtherStatus:
      example:
        finish_time: 2019-09-01T12:00:00+02:00
        start_time: 2019-09-01T12:00:00+02:00
        id: 918d693e-7cc1-45f7-bde2-e00cca32a5b1
        project_id: random-project-id
        status: passing
      properties:
        finish_time:
          format: date-time
          type: string
        start_time:
          format: date-time
          type: string
        id:
          format: uuid
          type: string
        project_id:
          type: string
        status:
          enum:
          - pending
          - failing
          - passing
          type: string
      required:
      - finish_time
      - id
      - project_id
      - start_time
      - status
      type: object
    ErrorReport:
      example:
        id: 1a9390e9-4ac5-4527-8e5e-05d2d153ada0
        json_payload: {}
        log_name: random-log-name
        receive_timestamp: 2019-09-01T12:00:00+02:00
        resource: {}
        source_location: {}
        text_payload: random-text-payload
        trace: random-trace
      properties:
        id:
          type: string
        json_payload:
          type: object
        log_name:
          type: string
        receive_timestamp:
          format: date-time
          type: string
        resource:
          type: object
        source_location:
          type: object
        text_payload:
          type: string
        trace:
          type: string
      required:
      - id
      - json_payload
      - log_name
      - receive_timestamp
      - resource
      - source_location
      - text_payload
      - trace
      type: object
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: X-API-KEY
      type: apiKey
      x-apikeyInfoFunc: openapi_server.controllers.security_controller_.info_from_ApiKeyAuth
