---
openapi: 3.0.2
info:
  title: Monitoring
  version: 1.0.0
  description: Endpoint to retreive all DAT Monitoring metrics
  contact:
    name: VolkerWessels Telecom - Digital Ambition Team
    url: 'https://vwt-digital.github.io/'
    email: opensource@vwt.digital
  license:
    name: GNU GPLv3
    url: 'https://www.gnu.org/licenses/gpl.txt'
servers:
- url: 'https://PROJECT_ID.appspot.com/'
  description: ""
security:
  - ApiKeyAuth: []
paths:
  /build-statuses-triggers:
    get:
      responses:
        200:
          $ref: '#/components/responses/BuildTriggerStatuses'
        204:
          description: No content
      summary: Get all build trigger statuses
      description: Get a list of all build trigger statuses
      x-openapi-router-controller: openapi_server.controllers.buildstatuses_controller
  /build-statuses-other:
    get:
      responses:
        200:
          $ref: '#/components/responses/BuildOtherStatuses'
        204:
          description: No content
      summary: Get last 20 other build statuses
      description: Get a list of last 20 other build statuses
      x-openapi-router-controller: openapi_server.controllers.buildstatuses_controller
  /error-reporting:
    get:
      responses:
        200:
          $ref: '#/components/responses/ErrorReporting'
        204:
          description: No content
      summary: Get last 20 error reportings
      description: Get a list of last 20 error reportings
      x-openapi-router-controller: openapi_server.controllers.errorreporting_controller
components:
  schemas:
    BuildTriggerStatus:
      required:
      - branch
      - git_source
      - organization
      - project_id
      - repo_name
      - status
      - updated
      type: object
      properties:
        branch:
          type: string
        git_source:
          type: string
        organization:
          type: string
        project_id:
          type: string
        repo_name:
          type: string
        status:
          enum:
          - pending
          - failing
          - passing
          type: string
        updated:
          format: date-time
          type: string
      example:
        branch: develop
        git_source: github
        organization: vwt-digital
        project_id: random-project-id
        repo_name: random-repo-name
        status: passing
        updated: 2019-09-01T12:00:00+02:00
    BuildOtherStatus:
      required:
      - finish_time
      - start_time
      - id
      - project_id
      - status
      type: object
      properties:
        finish_time:
          format: date-time
          type: string
        start_time:
          format: date-time
          type: string
        id:
          type: string
          format: uuid
        project_id:
          type: string
        status:
          enum:
          - pending
          - failing
          - passing
          type: string
      example:
        finish_time: 2019-09-01T12:00:00+02:00
        start_time: 2019-09-01T12:00:00+02:00
        id: 918d693e-7cc1-45f7-bde2-e00cca32a5b1
        project_id: random-project-id
        status: passing
    ErrorReport:
      required:
      - id
      - json_payload
      - log_name
      - receive_timestamp
      - resource
      - source_location
      - text_payload
      - trace
      type: object
      properties:
        id:
          type: string
        json_payload:
          type: object
        log_name:
          type: string
        receive_timestamp:
          format: date-time
          type: string
        resource:
          type: object
        source_location:
          type: object
        text_payload:
          type: string
        trace:
          type: string
      example:
        id: 1a9390e9-4ac5-4527-8e5e-05d2d153ada0
        json_payload: {}
        log_name: random-log-name
        receive_timestamp: 2019-09-01T12:00:00+02:00
        resource: {}
        source_location: {}
        text_payload: random-text-payload
        trace: random-trace
  responses:
    BuildTriggerStatuses:
      description: Scheme with multiple build trigger statuses
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/BuildTriggerStatus'
    BuildOtherStatuses:
      description: Scheme with multiple other build statuses
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/BuildOtherStatus'
    ErrorReporting:
      description: Scheme with multiple error reportings
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/ErrorReport'
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
